### ISSUE TITLE
Needs ad support

### ISSUE THREAD

**Issue by mdickin** [AyrA/is-working#1]
With a library this valuable, you can't risk it falling into disrepair. Please include ads in the npm console so that we can be sure `is-working` keeps working!

**Comment by jackharrhy** [comment]
also make sure to note if you are looking for a job when someone installs your package, how else will you make it in the job market otherwise?

**Comment by AyrA** [comment]
Any recommended ad providers? I want to do this properly.

**Comment by mdickin** [comment]
I mean, they're all the same really. Just provide a way to serve up external javascript and they can take care of the rest.

**Comment by mdickin** [comment]
Bad news folks, closing this issue now:

https://www.zdnet.com/article/npm-bans-terminal-ads/
